apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conference
spec:
  selector:
    matchLabels:
      app: conference
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: conference
    spec:
      containers:
      - name: conference
        image: iad.ocir.io/rodrigocandidosilva/conference
        imagePullPolicy: Always
        ports:
        - name: conference
          containerPort: 8081 #Endpoint is at port 8081 in the container
          protocol: TCP
        env:
        - name: CONFERENCE_NAME
          value: Oracle Code One
        - name: 'com.microprofile.conference.rest.SpeakerRestClient/mp-rest/url'
          value: http://${SPEAKER_SERVICE_HOST}:${SPEAKER_SERVICE_PORT}
      imagePullSecrets:
      - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: conference
  labels:
    app: conference
spec:
  type: LoadBalancer #Exposes the service
  ports:
  - port: 30001
    protocol: TCP
    targetPort: 8081
  selector:
    app: conference
---